title: Wujl
author: Aigars Dzerviniks
description: Notes.

highlighter: null
permalink: /:title

url: https://wu-30mki.github.io/
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: amber
